# Arquivo render.yaml CORRETO

services:
  #--------------------------------#
  #  Serviço para o Backend (API)  #
  #--------------------------------#
  - type: web
    name: backend-caralbum
    # ✅ ESTA LINHA É A CORRETA
    env: java             
    rootDir: backend
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/carAlbum-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production

  #----------------------------------#
  #  Serviço para o Frontend (Site)  #
  #----------------------------------#
  - type: web
    name: frontend-caralbum
    env: node
    rootDir: frontend
    plan: free
    buildCommand: yarn && yarn build
    startCommand: yarn start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: ${{backend-caralbum.url}}