# Arquivo render.yaml CORRIGIDO

services:
  #--------------------------------#
  #  Serviço para o Backend (API)  #
  #--------------------------------#
  - type: web
    name: backend-caralbum
    # CORREÇÃO 1: Trocado 'runtime' por 'env'
    env: java             
    rootDir: backend
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/carAlbum-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production

  #----------------------------------#
  #  Serviço para o Frontend (Site)  #
  #----------------------------------#
  - type: web
    name: frontend-caralbum
    env: node
    rootDir: frontend
    plan: free
    buildCommand: yarn && yarn build
    startCommand: yarn start
    envVars:
      # CORREÇÃO 2: Alterada a forma de obter a URL do backend
      - key: NEXT_PUBLIC_API_URL
        value: ${{backend-caralbum.url}} # Pega a URL do serviço 'backend-caralbum'